name: "Sorj-Net Controller Manager"
version: "1.2.40"
homeassistant: "2026.1.1"
slug: "sorj_net_manager"
description: "Dashboard para gerenciar dispositivos sorj-net.lightcontroller, estilo ESPHome."
url: "https://github.com/rosaldanha/ha-lightcontroller-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
boot: auto
# Habilita o acesso Ã  API do Supervisor e do Core
hassio_api: true
homeassistant_api: true
# Habilita a interface web no sidebar do HA (Ingress)
panel_icon: "mdi:chip"
ingress: true
ingress_port: 3000
options: {}
schema: {}
map:
  - config:rw
