name: "Sorj-Net Controller Manager"
version: "1.2.197"
homeassistant: "2026.1.1"
slug: "sorj_net_manager"
description: "Dashboard para gerenciar dispositivos sorj-net.lightcontroller, estilo ESPHome."
url: "https://github.com/rosaldanha/ha-lightcontroller-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
boot: auto
# Habilita o acesso Ã  API do Supervisor e do Core
hassio_api: true
homeassistant_api: true
hassio_role: homeassistant
# Habilita a interface web no sidebar do HA (Ingress)
panel_icon: "mdi:home-lightbulb"
panel: true

ingress: true
ingress_port: 3000

map:
  - config:rw
options:
  NUXT_ESPHOME_CONFIG_FOLDER: "../config/esphome" # esphomeConfigFolder
  NUXT_PUBLIC_SUPERVISOR_TOKEN: "error"
  NUXT_PUBLIC_WSS_URL: "error"

schema:
  NUXT_ESPHOME_CONFIG_FOLDER: str
  NUXT_PUBLIC_SUPERVISOR_TOKEN: str
  NUXT_PUBLIC_WSS_URL: str
